// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplatev2 = `{
    "schemes": {{ marshal .Schemes }},
    "components": {"schemas":{"v2.Book":{"properties":{"author":{"type":"string"},"id":{"type":"integer"},"title":{"type":"string"},"year":{"type":"integer"}},"type":"object"}}},
    "info": {"contact":{"email":"support@swagger.io","name":"API Support","url":"http://www.swagger.io/support"},"description":"{{escape .Description}}","license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"},"termsOfService":"http://swagger.io/terms/","title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {"/books":{"get":{"description":"get string by ID","requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}},"responses":{"200":{"content":{"application/json":{"schema":{"items":{"$ref":"#/components/schemas/v2.Book"},"type":"array"}}},"description":"ok"}},"summary":"Get a list of books in the the store"}}},
    "openapi": "3.1.0",
    "servers": [
        {"url":"/v2"}
    ]
}`

// SwaggerInfov2 holds exported Swagger Info so clients can modify it
var SwaggerInfov2 = &swag.Spec{
	Version:          "2.0",
	Title:            "Swagger Example API",
	Description:      "This is a sample server.",
	InfoInstanceName: "v2",
	SwaggerTemplate:  docTemplatev2,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov2.InstanceName(), SwaggerInfov2)
}
